name: "Test the Student App"

on:
 pull_request:
  branches: [master]

jobs:
 test_pull_request:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-node@v1
     with:
      node_version: 12
   - run: yarn install
   - run: yarn test
